package de.dhbw.erpbackend.domain;

public enum LogType {
    USER_REGISTERED,
    USER_CREATED,
    USER_LOGIN,
    USER_LOGOUT,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    LOCATION_CREATED,
    LOCATION_UPDATED,
    LOCATION_DELETED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,
    ITEM_CREATED,
    ITEM_SOLD,
    ITEM_WRITTEN_OFF,
    OTHER
}
